
/*#1. PRINT OUT THE EMPLOYEE NAME | DEPATURE DAY | RETURN DAY OF TRIPS : WHERE THE DEPATURE DAY IS A FRIDAY*/
SELECT EMPLOYEE.NAME, TO_CHAR(TRIP.DEP_DATE,'DAY', 'NLS_DATE_LANGUAGE=ENGLISH'), TO_CHAR(TRIP.RETURN_DATE,'DAY', 'NLS_DATE_LANGUAGE=ENGLISH'),TO_DATE(Return_Date,'DD/MM/YYYY') - TO_DATE(Dep_Date,'DD/MM/YYYY') "DAYS" FROM EMPLOYEE INNER JOIN TRIP ON EMPLOYEE.ID = TRIP.EMP_ID WHERE TO_CHAR(DEP_DATE,'DY', 'NLS_DATE_LANGUAGE=ENGLISH') IN ('FRI');

/*#2. PRINT THE # OF EMPLOYEE WHO RETURNED FROM A TRIP DURING LAST WEEKEND [FROM TODAY'S WEEK]*/
SELECT COUNT(TRIP.ID) FROM TRIP WHERE TRIP.Return_Date BETWEEN SYSDATE - 9 AND SYSDATE AND  TO_CHAR(TRIP.RETURN_DATE,'DY') IN ('FRI','SAT','SUN');

/*#3. RECEIPTS SUBMITTED IN 2017: PRINT TOTATL AMT FOR EACH EXPENSE TYPE: PRINT OUT THE FULL WORDS OF T/H/M */
SELECT EXPENSE.TYPE, SUM(EXPENSE.AMOUNT) FROM EXPENSE WHERE TO_CHAR(SUBMITTED,'YYYY') IN ('2017') GROUP BY TYPE;

/*#4. EVERY EMP SHOW TOTAL # OF TRIPS TAKEN. SHOW NAME|# OF TRIPS. IF NONE PRINT NAME & 0.*/
SELECT NVL(EMPLOYEE.NAME,0), COUNT(TRIP.ID) FROM TRIP RIGHT JOIN EMPLOYEE ON EMPLOYEE.ID = TRIP.EMP_ID GROUP BY NAME;
