DECLARE
  INSERT_EMP_ID INTEGER;
  INSERT_TO_CITY DATE;
  INSERT_DEP_DATE DATE;
  INSERT_RETURN_DATE DATE;
  INSERT_EST_COST DECIMAL(6,2);
  COUNTER NUMBER;
BEGIN
  INSERT_EMP_ID       :=  &INSERT_EMP_ID;
  INSERT_TO_CITY      :=  &INSERT_TO_CITY;
  INSERT_DEP_DATE     :=  &INSERT_DEP_DATE;
  INSERT_RETURN_DATE  :=  &INSERT_RETURN_DATE;

  dbms_output.put_line('EMPLOYEE ID : ' || INSERT_EMP_ID);
  dbms_output.put_line('TO CITY : '     || INSERT_TO_CITY);
  dbms_output.put_line('Dep DATE: '     || INSERT_DEP_DATE);
  dbms_output.put_line('RET DATE: '     || INSERT_RETURN_DATE);
  SELECT COUNT(*) INTO COUNTER FROM TRIP WHERE EMP_ID = INSERT_EMP_ID;
  dbms_output.put_line('NO SUCH EMP');


END;
/
  -- PROMPT INSERTING A TRIP FOR EMPLOYEE;
  -- PROMPT;
  -- PROMPT #2: INSERT EMP_ID: ;
  -- PROMPT #3: INSERT TO_CITY: ;
  -- PROMPT #4: INSERT DEP_DATE: ;
  -- PROMPT #5: INSERT RETURN_DATE: ;
  -- PROMPT #6: INSERT EST_COST: ;
